port: 4000
baseurl: /
url: http://danhough.com
permalink: /blog/:title/
encoding: utf-8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

gems: [ "jemoji" ]
